<?php
// =========================================================================
// setup.php - ONE-TIME DATABASE INSTALLER
// =========================================================================
// Open this in your browser: http://localhost/invoxa-simple/setup.php
// It will create the database, tables, seed data, and a default admin user.
// =========================================================================

$message = '';
$status = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_user = trim($_POST['db_user'] ?? 'root');
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = trim($_POST['db_name'] ?? 'invoice_management');

    try {
        // Connect to MySQL (without selecting a database yet)
        $pdo = new PDO("mysql:host=$db_host;charset=utf8mb4", $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Create the database
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$db_name`");

        // Run the schema
        $schemaFile = __DIR__ . '/schema.sql';
        if (!file_exists($schemaFile)) throw new Exception("schema.sql not found");
        $pdo->exec(file_get_contents($schemaFile));

        // Write the config file
        $configContent = "<?php\n"
            . "// Auto-generated by setup.php on " . date('Y-m-d H:i:s') . "\n\n"
            . "define('DB_HOST', '" . addslashes($db_host) . "');\n"
            . "define('DB_USER', '" . addslashes($db_user) . "');\n"
            . "define('DB_PASS', '" . addslashes($db_pass) . "');\n"
            . "define('DB_NAME', '" . addslashes($db_name) . "');\n";
        file_put_contents(__DIR__ . '/backend/db_config.php', $configContent);

        // Create default admin user
        $check = $pdo->prepare("SELECT id FROM users WHERE email = :email");
        $check->execute(['email' => 'admin@invoxa.com']);
        if (!$check->fetch()) {
            $hash = password_hash('admin123', PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("INSERT INTO users (first_name, last_name, email, password_hash, role) VALUES ('Admin', 'User', :email, :hash, 'admin')");
            $stmt->execute(['email' => 'admin@invoxa.com', 'hash' => $hash]);
            $userId = $pdo->lastInsertId();

            // Insert sample invoices
            $mocks = [
                ['Maroc Telecom', 1250.00, 'Fibre Optique internet monthly subscription', '2023-10-24', null, 1],
                ['Marjane', 4500.00, 'Office breakroom appliances and supplies', '2023-10-22', '2023-10-23 09:15:00', 2],
                ['Electroplanet', 850.00, 'Spare monitors and keyboard updates', '2023-05-10', null, 2],
                ['Boutique Essalam', 120.50, 'Paper, notebooks, and stationery', '2023-10-18', '2023-10-19 14:30:00', 4],
                ['Attijariwafa Bank', 3200.00, 'Financial consulting and advisory fees', '2023-10-15', '2023-10-16 11:00:00', 3],
                ['Inwi', 4500.00, 'Mobile plans and 4G routers', '2023-10-24', '2023-10-24 16:00:00', 1],
                ['Maroc Bureau', 12000.00, 'Office desks, chairs, meeting tables', '2023-10-20', '2023-10-20 10:00:00', 4],
                ['Redal', 3250.00, 'Monthly electricity and water utility', '2023-10-15', '2023-10-15 15:30:00', 5],
            ];
            $ins = $pdo->prepare("INSERT INTO factures (title, amount, description, invoice_date, paid_at, user_id, category_id) VALUES (:t, :a, :d, :id, :pa, :uid, :cid)");
            foreach ($mocks as $m) {
                $ins->execute(['t'=>$m[0], 'a'=>$m[1], 'd'=>$m[2], 'id'=>$m[3], 'pa'=>$m[4], 'uid'=>$userId, 'cid'=>$m[5]]);
            }
        }

        $status = 'success';
        $message = "Database installed successfully!<br><br><strong>Default Login:</strong><br>Email: <code>admin@invoxa.com</code><br>Password: <code>admin123</code>";

    } catch (Exception $e) {
        $status = 'error';
        $message = "Installation failed: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - Invoxa</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root { --primary: #1C335C; --secondary: #0078BB; --bg: #F2F5F9; --white: #fff; }
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Poppins',sans-serif; background:var(--bg); display:flex; justify-content:center; align-items:center; min-height:100vh; padding:20px; }
        .container { background:var(--white); max-width:500px; width:100%; border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.05); padding:40px; text-align:center; }
        .logo { display:flex; justify-content:center; align-items:center; gap:10px; margin-bottom:20px; }
        .logo-box { background:var(--primary); color:var(--white); width:45px; height:45px; border-radius:10px; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:24px; }
        .logo h1 { font-size:24px; color:var(--primary); font-weight:700; text-align:left; line-height:1; }
        .logo span { font-size:11px; color:var(--secondary); font-weight:500; text-transform:uppercase; letter-spacing:1px; display:block; text-align:left; }
        h2 { font-size:22px; color:var(--primary); margin-bottom:10px; }
        p.intro { font-size:14px; color:#666; margin-bottom:30px; }
        .form-group { text-align:left; margin-bottom:20px; }
        label { display:block; font-size:12px; font-weight:600; color:var(--primary); margin-bottom:6px; text-transform:uppercase; letter-spacing:0.5px; }
        input { width:100%; padding:12px 16px; border:1px solid #ddd; border-radius:8px; font-family:inherit; font-size:14px; outline:none; }
        input:focus { border-color:var(--secondary); box-shadow:0 0 0 3px rgba(0,120,187,0.1); }
        .btn { background:var(--secondary); color:var(--white); border:none; width:100%; padding:14px; border-radius:8px; font-family:inherit; font-size:15px; font-weight:600; cursor:pointer; margin-top:10px; text-decoration:none; display:block; text-align:center; }
        .btn:hover { background:var(--primary); }
        .alert { padding:16px; border-radius:8px; font-size:14px; text-align:left; margin-bottom:24px; line-height:1.5; }
        .alert-success { background:#e6f6ee; color:#1b8a5a; border:1px solid #d4eedf; }
        .alert-error { background:#fde8e8; color:#e53e3e; border:1px solid #fcd3d3; }
        code { background:rgba(0,0,0,0.05); padding:2px 6px; border-radius:4px; font-family:monospace; font-size:13px; }
    </style>
</head>
<body>
<div class="container">
    <div class="logo"><div class="logo-box">i</div><div><h1>invoxa</h1><span>Management Pro</span></div></div>
    <h2>Database Installation</h2>
    <p class="intro">Fill in your MySQL settings to create the database, tables, and demo data.</p>

    <?php if (!empty($message)): ?>
        <div class="alert alert-<?= $status ?>"><?= $message ?></div>
    <?php endif; ?>

    <?php if ($status !== 'success'): ?>
        <form method="POST">
            <div class="form-group"><label>MySQL Host</label><input type="text" name="db_host" value="localhost" required></div>
            <div class="form-group"><label>Database Name</label><input type="text" name="db_name" value="invoice_management" required></div>
            <div class="form-group"><label>Username</label><input type="text" name="db_user" value="root" required></div>
            <div class="form-group"><label>Password</label><input type="password" name="db_pass" placeholder="Empty by default on XAMPP"></div>
            <button type="submit" class="btn">Configure & Install</button>
        </form>
    <?php else: ?>
        <a href="login.php" class="btn">Go to Login Page</a>
    <?php endif; ?>
</div>
</body>
</html>
